### ISSUE TITLE
Solid phase is overwritten - geometrical limitations of inlet?

### ISSUE THREAD

**Issue by to3sk** [OPM/LBPM#40]
Hi,

I am trying to simulate the two phase flow in a simple channel with a dead end. When I run the LBPM my solid phase is overwritten by a fluid near inlet. Attached you can find an example.

![Inlet](https://user-images.githubusercontent.com/87967782/129900206-5e96be88-d309-42cc-bb56-955eedfd2c17.jpg)

Are there any geometrical limitations on the shape of the inlet? Do I need to create a dummy cell that is filled with the fluid phase?

I would also be thankful if you could refer me to the source where I can find all keywords for BC.

Thank you

**Comment by JamesEMcClure** [comment]
LBPM always assigns the inlet / outlet in the z-direction if you are using an external boundary condition.  These
are usually `BC=3` or `BC=4` for `lbpm_color_simulaotr`. This is done so that each region is a contiguous memory region. If you drive the flow in the z direction, then you should be able to run this geometry without overwriting the solid layer. 

You could also drive the flow with an external body force by setting `BC=0` in which case you can drive the fluids in either the `x`, `y` or `z` directions. 

See this link for BC keywords for the color simulator

https://github.com/OPM/LBPM/blob/master/docs/source/userGuide/models/color/index.rst

**Comment by to3sk** [comment]
My flow was in the z direction.
Thank you for the answer.
