### ISSUE TITLE
How can I run a single-phase simulation with pressure boundary conditions?

### ISSUE THREAD

**Issue by sadafsobhani** [OPM/LBPM#8]

**Comment by JamesEMcClure** [comment]
Currently the pressure boundary condition is disabled within lbpm_permeability_simulator. This is because the approach to steady state will generally be faster if the flow is driven by an external body force. 

If needed, it would be possible to implement the pressure BC in the same way that it is implemented for lbpm_color_simulator:

Option 1. Set the pressure values directly at the boundary (BC=2)
Option 2. Use the flux "consistency condition" to choose the pressure such that desired volumetric flow rate is achieved (BC=4)
